version: '3.8'
services:
  client:
    stdin_open: true
    tty: true
    container_name: react_app
    build: 
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - 8100:8100
    volumes:
      - /app/node_modules
      - ./:/app


